AWSTemplateFormatVersion: '2010-09-09'

Description: VPC and LoadBalancer

Resources:

  VPC:

    Type: AWS::EC2::VPC

    Properties:

      CidrBlock: 10.0.0.0/16

  Subnet:

    Type: AWS::EC2::Subnet

    Properties:

      VpcId: !Ref VPC

      CidrBlock: 10.0.1.0/24

      MapPublicIpOnLaunch: true

      AvailabilityZone: !Select [0, !GetAZs '']

  IGW:

    Type: AWS::EC2::InternetGateway

  AttachGateway:

    Type: AWS::EC2::VPCGatewayAttachment

    Properties:

      VpcId: !Ref VPC

      InternetGatewayId: !Ref IGW

  LoadBalancer:

    Type: AWS::ElasticLoadBalancingV2::LoadBalancer

    Properties:

      Name: MyALB

      Subnets:

        - !Ref Subnet

      Scheme: internet-facing

      Type: application
 
