AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Tomcat with WAR in existing VPC

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  KeyName:
    Description: EC2 KeyPair for SSH access
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  TomcatInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-02457590d33d576c3   # Replace with your region's Amazon Linux 2 AMI
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref SubnetId
          GroupSet:
            - !Ref SecurityGroupId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y java-11-amazon-corretto-headless wget tomcat
          systemctl enable tomcat
          systemctl start tomcat
          wget http://172.31.87.228:8081/artifactory/libs-snapshot-local/your-app.war -O /usr/share/tomcat/webapps/your-app.war
